### PR TITLE
Change back button overrideability

### PR DESCRIPTION
**Pull request by bdorfman-stripe**
Change left bar button item logic so its
1. Cancel by default.
2. Overidden to back in viewWillAppear for non-root VC's
3. Not overidden for root VC's

This allows people to change the left bar item after init for views that aren't in root (if it's not going to be presented as a modal and thus does not make sense to have a cancel).

Fixes the use case described in https://github.com/stripe/stripe-ios/issues/507 while still doing automatic back/cancel logic for existing usage.

r? @jack-stripe

### CODE REVIEW

**Comment by jack-stripe** [comment]
lgtm! you'll probably need to make a new branch to fix these snapshot tests and rebase off that in order to get a green build.

**Comment by bdorfman-stripe** [comment]
Sounds good. Gonna open a new pr to fix the unrelated snapshot test issues shortly.

**Comment by bdorfman-stripe** [comment]
These snapshot failures are actually because previously the way they were captured, there was no left bar button item in the snapshot (due to how the test fakes a view controller for presentation at the correct size, and doesn't actually run in an app). After these changes, they now have a Cancel button since its set earlier in the lifecycle and not on view did load. I think this is actually what we want, and can just re-record the images? Nothing else seems to be different in them, let me know what you think.

**Comment by jack-stripe** [comment]
cool, sounds good, re-record away

**Pull request merged**
