### PR TITLE
Change our podspec to use a resource bundle

### PR DESCRIPTION
**Pull request by bdorfman**
Changing to use a named Stripe.bundle like for manual/Fabric installation so that we don't clobber people's resources when they use non-framework Cocoapods installs. Since our code is already set up to look for a `Stripe.bundle` everywhere relevant this should require no other code changes.

### CODE REVIEW

**Comment by benzguo** [comment]
👍

**Comment by bdorfman** [comment]
This is actually broken because Cocoapods will also still make Stripe.bundle even when using dynamic frameworks, and we don't expect that. Will need to rewrite bundle locator code to check for this case as well before merging.

**Comment by bdorfman** [comment]
Pushed more updates to this @bg if you want to take another look.

**Comment by bdorfman** [comment]
Pushed more updates to this @benzguo if you want to take another look

**Comment by benzguo** [comment]
ah word, good catch – lgtm!

**Pull request merged**
