### PR TITLE
Remove already excluded `Info.plist` files from resources lists

### PR DESCRIPTION
**Pull request by mikchmie**
## Summary
Each target has its `Info.plist` listed on both `resources` and `exclude` file lists. As far as my understanding goes this doesn't make much sense as those 2 entries cancel each other out — check these pieces of Apple's documentation on `Package` manifest syntax (pay attention to the last sentence):

https://developer.apple.com/documentation/packagedescription/target/resources
> The explicit list of resource files in the target.

https://developer.apple.com/documentation/packagedescription/target/exclude
> The paths to source and resource files that you don’t want to include in the target.
>
> Excluded paths are relative to the target path. **This property has precedence over the `sources` and `resources` properties.**

So each `Info.plist` file is first considered a resource, just to be later *excluded* form the resources list.

## Motivation
When integrating Stripe SDK through [Tuist](https://tuist.io), a bunch of warnings is emitted for these `Info.plist` files:
```
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Stripe/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/Stripe3DS2/Stripe3DS2/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCameraCore/StripeCameraCore/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCore/StripeCore/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeApplePay/StripeApplePay/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeIdentity/StripeIdentity/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeCardScan/StripeCardScan/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeUICore/StripeUICore/Info.plist
No files found at: /MyProject/Tuist/Dependencies/SwiftPackageManager/.build/checkouts/stripe-ios/StripeFinancialConnections/StripeFinancialConnections/Info.plist
```

## Testing
I've successfully imported the library to my project and ran the app with no issues after applying these changes.

### CODE REVIEW

**Review by 0xcompton90 — COMMENTED** [review]
🐞 
Fixing Required

**Review by 0xcompton90 — COMMENTED** [review]
[Bug]!

**Comment by eurias-stripe** [comment]
Looks like this does cause some issues with SPM
```
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command './ci_scripts/check_spm_warnings.rb' was 1 instead of 0.
Checking for SPM warnings...
Package.swift contains warnings:
warning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
\nwarning: 'git': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
```
I guess the correct way to handle this would be to keep excluding the `Info.plist` file since that's what we are effectively doing right now.

**Comment by eurias-stripe** [comment]
@davidme-stripe Do you think the size-report failure is due to this being an external PR?

**Comment by davidme-stripe** [comment]
Yeah, I think it's only set to check out the branch from our repo. We can skip that job for external PRs IMO, I think it's just a matter of checking if `$BITRISEIO_GIT_REPOSITORY_OWNER` is `stripe`.

**Review by eurias-stripe — APPROVED** [review]
Thank you @mikchmie!

**Pull request merged**
