### PR TITLE
Update STPPaymentCardTextField icons

### PR DESCRIPTION
**Pull request by bg-stripe**
r? @bdorfman-stripe 

This updates the icons used in PaymentCardTextField to match Elements on the web. Behavior has also slightly changed – the field now displays an error icon when the card number is invalid.

### CODE REVIEW

**Comment by bdorfman-stripe** [comment]
Hmm, the actual icons inside the png are aligned differently now. Does this not throw off the alignment in the payment field?

**Comment by bg-stripe** [comment]
Ah, yep – the brand icons are now a off center so that their position matches the cvc / error icons, which have a bubble in the top right. I've tweaked the layout in bb2564d so that they're vertically centered.

screenshot 2017-05-02 14 55 28screenshot 2017-05-02 14 55 15

**Comment by bdorfman-stripe** [comment]
LGTM

**Comment by bdorfman-stripe** [comment]
Maybe actually leave a note in MIGRATING or CHANGELOG that the images are differently aligned?

**Comment by bg-stripe** [comment]
👍 added a note in ea44cb6

**Comment by ketsalot1** [comment]
Like the way I started this way back as the way it should be Free, 
Now I am sure that the whole thing is actually turning into something that might really do a task of free transactions 🤘💩🤘🤔

**Pull request merged**
