### PR TITLE
Move UIImage+Stripe.h to public headers

### LINKED ISSUE #301: Unable to import "UIImage+Stripe.h"
Other categories work, but `UIImage+Stripe.h` does not.
Looks like the reason is it is not  in PublicHeaders folder.

### PR DESCRIPTION
**Pull request by benzguo**
r? @jflinter 

Fixes #301 :/

I've also added an `#import <Stripe/UIImage+Stripe.h>` to the cocoapods test project.

### CODE REVIEW

**Comment by jflinter** [comment]
LGTM. Do you have any Feelings on how we could catch this automatically next time?

**Comment by benzguo** [comment]
I've imported the header in the cocoapods test project – perhaps we should add imports for all public headers?

**Comment by jflinter** [comment]
That seems like a reasonable first step.

**Comment by benzguo** [comment]
en-phabbed: https://phab.stripe.com/T18617

**Pull request merged**
