### PR TITLE
Enable deleting selected card

### LINKED ISSUE #1032: Enable deleting selectedPaymentMethod.
## Summary

From the stripe api [documentation](https://stripe.com/docs/api/cards/delete), the user can delete the selected card, but this is not allowed in the sdk, why this ?
```
if (paymentMethod == self.selectedPaymentMethod) {
    // Cannot detach selected payment method
    return YES;
}
```

## Code to reproduce
```
if (paymentMethod == self.selectedPaymentMethod) {
    // Cannot detach selected payment method
    return YES;
}
```

## iOS version
iOS 12

## Installation method
Pod

## SDK version
13.2.0

### PR DESCRIPTION
**Pull request by wangjiejacques**
## Summary
Enable deleting selected card, This closes #1032.

## Motivation
Some user want to delete their selected card.

## Testing
As a user, I can delete the selected card.

### CODE REVIEW

**Comment by csabol-stripe** [comment]
Thanks for the request and patch. We had initially deliberately disabled removing the selected payment method, but we are going to reevaluate that.

**Comment by mconbere** [comment]
@csabol-stripe Can we get an update on the status of this pull request? We recently switched to the standard Stripe integration and are receiving many user complaints about this issue.

**Comment by csabol-stripe** [comment]
Thanks for the additional signal @mconbere I've included this in our task tracking system and will make sure it's discussed at our next regular planning meeting

**Comment by machinegunhairy** [comment]
@csabol-stripe It seems like this is getting close to being merged, is that something that may happen soon, do you know? We're trying to role out Stripe as a new payment system with our software, but this is a feature that we've been asked to include.

**Comment by csabol-stripe** [comment]
@machinegunhairy we are working on including this in our next SDK release!

**Comment by csabol-stripe** [comment]
I've created an updated pull request for this issue. Going to close this one. Thanks! https://github.com/stripe/stripe-ios/pull/1149

**Pull request closed without merging**
