### PR TITLE
Update to recommended settings

### PR DESCRIPTION
**Pull request by benzguo**
r? @jflinter

### CODE REVIEW

**Comment by jflinter** [comment]
This isn't a very... reviewable change?

**Comment by benzguo** [comment]
true. I usually err on the side of making PRs just so changes are more visible, but I'll just push things like this in the future.

**Comment by jflinter** [comment]
Yeah, I am pro-PR here! Just doesn't have to block on my reviewing it : )

**Comment by benzguo** [comment]
ah, cool. :)

**Pull request merged**
