### PR TITLE
[Identity] Support phone verification

### PR DESCRIPTION
**Pull request by ccen-stripe**
## Summary

This is the release branch for Identity phone verification, will merge it to master once it's feature complete. See more details in this internal [doc](https://docs.google.com/document/d/1MiThhOl-nntB3LFOPlTwUb1kAhqvbO9zPCD1s_gvMZk/edit#).

The release branch has two sets of changes - 

1. Changes in the SDK to support phone Verification - all changes are reviewed before merged into this branch, see details [here](https://github.com/stripe/stripe-ios/pull/2452#issuecomment-1613663569)

2. Changes in the example app to support Phone verification
    * [type](https://site-admin.stripe.com/docs/api/identity/verification_sessions/object#identity_verification_session_object-type)=`phone`:  
        * UX: Added a "Fallback with document" section to provide fallback option to document, when turned on, display a "OTP check" dropdown with `none` | `attempt` | `required` value, display a section to configure document fallback
        * API: Sets [options.phone_otp.check](https://site-admin.stripe.com/docs/api/identity/verification_sessions/create#create_identity_verification_session-options-phone_otp-check) with `none` | `attempt` | `required`, sets [options.phone_records.fallback](https://site-admin.stripe.com/docs/api/identity/verification_sessions/create#create_identity_verification_session-options-phone_records-fallback) = `document`, sets [options.document](https://site-admin.stripe.com/docs/api/identity/verification_sessions/create#create_identity_verification_session-options-document)
    * [type](https://site-admin.stripe.com/docs/api/identity/verification_sessions/object#identity_verification_session_object-type)=`document` | `id_number` - **!temporarily on hold until backend supports PII**, tracked in [M2](https://docs.google.com/document/d/1MiThhOl-nntB3LFOPlTwUb1kAhqvbO9zPCD1s_gvMZk/edit#bookmark=id.4ax92z39ckup): 
        * UX: Added "Require phone number" section to provide a number upfront
        * API: Turns on [options.phone.require_verification](https://site-admin.stripe.com/docs/api/identity/verification_sessions/create#create_identity_verification_session-options-phone-require_verification) and sets [provided_details.phone](https://site-admin.stripe.com/docs/api/identity/verification_sessions/create#create_identity_verification_session-provided_details-phone) for the API

See a similar Android change at https://github.com/stripe/stripe-android/pull/6438
# Motivation

Support [phone verification](https://stripe.com/docs/identity/phone)

# Testing

- [x] Added tests
- [x] Modified tests
- [x] Manually verified

# Recording
| PhoneV flow  |
| ------------- |
| iOSPhone |

## Changelog

- [Added] Identity - support phone verification.

### CODE REVIEW

**Comment by ccen-stripe** [comment]
The following reviewed PRs are merged into this release branch:
https://github.com/stripe/stripe-ios/pull/2649
https://github.com/stripe/stripe-ios/pull/2654
https://github.com/stripe/stripe-ios/pull/2669

**Comment by vardges-stripe** [comment]
As I'm going on leave soon, passing on to @kgaidis-stripe for building context.

**Review by kgaidis-stripe — APPROVED** [review]
based off DM discussions with ccen, this just requires a rubber stamp as all the PR's have been reviewed separately:

https://github.com/stripe/stripe-ios/pull/2452#issuecomment-1613663569

I did have a quick scan too regardless

**Comment by yuki-stripe** [comment]
@ccen-stripe FYI please squash and merge next time to avoid polluting the commit log too much (see https://github.com/stripe/stripe-ios/commits/master) - ty!

**Pull request merged**
