### PR TITLE
Include UI source files in podspec

### PR DESCRIPTION
**Pull request by bradfol**
The pod is currently missing UI implementation files

### CODE REVIEW

**Comment by jflinter** [comment]
:facepalm: thanks, @bradfol.

**Comment by bradfol** [comment]
Crap, now time for my own facepalm
`{h.m}` should be `{h,m}`

**Comment by jflinter** [comment]
facepalm ^ 2 (merged)

**Comment by bradfol** [comment]
Thanks, project is now building with this podspec

**Pull request merged**
