### PR TITLE
Financial Connections: fixed an issue where playground app could crash due to invalid setup

### PR DESCRIPTION
**Pull request by kgaidis-stripe**
## Summary

We experienced a [crash](https://stripe.slack.com/archives/C02KW8G938W/p1683901990067859) with playground app setup, so this ensures this is handled gracefully in the future.

## Testing

Simulator Screen Shot - iPhone 13 mini - 2023-05-12 at 16 58 04

Simulator Screen Shot - iPhone 13 mini - 2023-05-12 at 16 57 35

### CODE REVIEW

**Review by vardges-stripe — APPROVED** [review]
tnx

**Comment by kgaidis-stripe** [comment]
closed/re-opened to re-run stuck `license/cla`

**Pull request merged**
