### PR TITLE
Add modalPresentationStyle to STPPaymentContext

### PR DESCRIPTION
**Pull request by benzguo**
r? @jflinter 

A user wrote in requesting this feature.

### CODE REVIEW

**Comment by jflinter** [comment]
Neat, this is cool. How does this work with the SMS code view controller?

**Comment by benzguo** [comment]
At the moment, the SMS code view controller just inherits the add card view controller's modal presentation style [0]. The SMS screen looks kinda odd full screen on a horizontal iPad – we could consider always making it a PageSheet...





[0] https://github.com/stripe/stripe-ios/blob/bg-modal-presentation/Stripe/STPAddCardViewController.m#L463

**Comment by jflinter** [comment]
Yeah, FullScreen SMS view controller looks bad. I'm open to anything that looks reasonable on both iPhone and iPad (it looks like the half-grey background stacks with FullScreen; it'd be nice to avoid that).

**Comment by benzguo** [comment]
Cool. Let's go with FormSheet [0] – it's narrower than PageSheet. Both are a no-op on iPhone.

[0] https://github.com/stripe/stripe-ios/pull/405/commits/c3fa26376b059314d994098cc9d467deb2752527

simulator screen shot aug 16 2016 6 09 25 pm

simulator screen shot aug 16 2016 6 20 11 pm

**Comment by jflinter** [comment]
Nice, that looks better to me!

**Pull request merged**
