### PR TITLE
Add custom footer view support

### PR DESCRIPTION
**Pull request by irace**
## Summary

Adds the ability to provide a custom footer view that will be added to the view controllers managed by the Stripe SDK.

## Motivation

https://github.com/stripe/stripe-ios/issues/756

## Testing

Call `setFooterView:` on either `STPPaymentMethodsViewController` or `STPPaymentContext`

### CODE REVIEW

**Comment by bdorfman-stripe** [comment]
Hey @irace,

Thanks for the pull request! We really appreciate the work you've put into this. Below is some feedback and questions/suggestions we have.

Why the separation between the footer view callbacks for payment methods VC and STPSizedViewProvider? (`paymentMethodsViewController:footerViewForWidth:` vs `sizedViewForWidth:`). Can these be combined into a single callback/protocol? Assuming we merge these two APIs, can we add `customFooterViewProvider` to the `STPFooterViewSupporting` protocol, and perhaps rename that protocol to `STPCustomFooterViewSupporting`?

e.g.
```@protocol STPCustomFooterViewSupporting
@property (nonatomic) id<STPSizedViewProvider> customFooterViewProvider;
- (void)setCustomFooterView:(UIView *)footerView;
@end
```

Should the STPPaymentContext callback provide some sort of info on what view is showing the footer? (Add Card Vs Payment Methods vs any other screen we might want to expand footer support to, such as shipping view). Perhaps an enum value?

It seems like this code assumes the width of the view controller will never change, as the width is only provided once. Perhaps just a comment mandating that the passed in views properly implement `sizeThatFits:` and use that to resize the footers in the our view controllers' `viewDidLayoutSubviews`?

Let us know if these proposed changes make sense based on how your app will be using this feature. Thanks again for your help!

**Comment by irace** [comment]
> Why the separation between the footer view callbacks for payment methods VC and STPSizedViewProvider? (`paymentMethodsViewController:footerViewForWidth:` vs `sizedViewForWidth:`). Can these be combined into a single callback/protocol?

Yeah, I’m not thrilled with the differences here either. Basically, the view controller can ask for a sized footer synchronously via its delegate protocol, where `STPPaymentContext` doesn’t currently have a delegate protocol (and I didn’t want to add one), so I needed to come up with an abstraction (`STPSizedViewProvider`) that would allow it to ask asynchronously later on, when needed.

In the interest of uniformity, we could change the view controller delegate method to return an object conforming to `STPSizedViewProvider` instead of a `UIView`? In this case, the width wouldn’t even need to leak into the delegate API.

The downside is that this would be an additional layer of abstraction that could be somewhat confusing to someone who is only using the view controller delegate, and not `STPPaymentContext`. They might wonder why they need to create a new type that vends a `UIView` (`STPSizedViewProvider`) instead of just vending the `UIView` themselves. But this doesn’t seem like a huge deal to me. I‘m happy to make this change if you’d like 👍.

> Should the STPPaymentContext callback provide some sort of info on what view is showing the footer? (Add Card Vs Payment Methods vs any other screen we might want to expand footer support to, such as shipping view). Perhaps an enum value?

Sure, can’t hurt.

> It seems like this code assumes the width of the view controller will never change, as the width is only provided once. Perhaps just a comment mandating that the passed in views properly implement sizeThatFits: and use that to resize the footers in the our view controllers' viewDidLayoutSubviews?

Hmmm - in this case would we ditch `STPSizedViewProvider` altogether in favor of just passing around `UIView` instances that can size themselves?

**Comment by bdorfman-stripe** [comment]
I think requiring people pass views around that size themselves solves several issues if you think that's a reasonable solution. I think it also avoids some of the delegate problems you describe (as now you can just have a property for the view and don't need a callback that passes the width).

**Comment by irace** [comment]
Yeah, I totally agree. Let me see if I can make this work.

**Comment by irace** [comment]
@bdorfman-stripe OK, I ended up simplifying this quite a bit and unifying on simply using setters and objects that all conform to `STPFooterViewSupporting` instead of having multiple ways to do this. 

In the interest of keeping this simple, I didn’t end up using delegation which means I didn’t end up having a method to pass a “screen type” parameter to after all. This could be added in the future but I didn’t want to prematurely add complexity that may not actually prove useful.

Feedback welcome!

**Comment by bdorfman-stripe** [comment]
Looks pretty good to me! We can take it the rest of the way fixing it to pass our CI tests and adding new tests for the new API if you'd like. Thanks for your help!

**Comment by bdorfman-stripe** [comment]
Closing this in favor of https://github.com/stripe/stripe-ios/pull/792. Still working on some tweaks and adding tests, but hopefully ready to ship soon. Thanks again for your work on this @irace !

**Pull request closed without merging**
