### PR TITLE
Add BDCC to analytics payload

### PR DESCRIPTION
**Pull request by eurias-stripe**
## Summary
Add analytics for BDCC.
This will add fields to the `payment_sheet_configuration` column.

## Motivation
Part of BDCC

## Testing
Checked splunk for the event

### CODE REVIEW

**Review by sfriedman-stripe — COMMENTED** [review]
How does this manifest, as another column in the analytics table or as part of a JSON payload? I think @yuki-stripe was asking @randyshort-stripe about this in the metrics channel. Would be good to have details in the PR description about how you're approaching this

**Comment by eurias-stripe** [comment]
> How does this manifest, as another column in the analytics table or as part of a JSON payload?

It will appear as part of the JSON payload in the `payment_sheet_configuration` column ([example query](https://hubble.corp.stripe.com/queries/eurias/f438fd5f))

**Review by porter-stripe — APPROVED** [review]
Adding it to the payment sheet configuration makes sense here to me.

**Comment by sfriedman-stripe** [comment]
> > How does this manifest, as another column in the analytics table or as part of a JSON payload?
> 
> It will appear as part of the JSON payload in the `payment_sheet_configuration` column ([example query](https://hubble.corp.stripe.com/queries/eurias/f438fd5f)).
> 
> I don't think it would make sense to add another column for this, it should just be logged along with the rest of the configuration.

Chatted about this with @randyshort-stripe in Slack and agreed to just add it to the JSON config

**Review by sfriedman-stripe — APPROVED** [review]

**Pull request merged**
