### PR TITLE
Bump test ios version

### PR DESCRIPTION
**Pull request by bdorfman-stripe**
Remove accidentally added file.
Also update tests to run on newest ios version.

### CODE REVIEW

**Comment by bg-stripe** [comment]
heh, I did the same in https://github.com/stripe/stripe-ios/pull/559 – we can use this one though since it also has the version update

**Comment by bdorfman-stripe** [comment]
Oh sorry, I totally missed your other PR

**Comment by bdorfman-stripe** [comment]
Other pr is merged, so now this is just changing the tests ios version

https://github.com/stripe/stripe-ios/pull/559

**Comment by bdorfman-stripe** [comment]
Travis's xcode8.2 image seems to not understand the "latest" property for finding ios simulators? Not sure what's up and don't want to debug atm so just closing this for now as the build break fix is already in.

**Pull request closed without merging**
