### PR TITLE
Remove Xcode 13 support

### PR DESCRIPTION
**Pull request by davidme-stripe**
## Summary
* Drop support for Xcode 13
* Stop running iOS 13 tests, as XCTest no longer supports iOS 13.7 on Ventura. This seems unintentional and is reproducible with a basic test app, so I've filed FB12099175.

## Motivation
https://developer.apple.com/news/upcoming-requirements/

## Testing
Existing CI tests

## Changelog
Added a note to the changelog.

### CODE REVIEW

**Review by jaimepark-stripe — DISMISSED** [review]
🔥

**Comment by davidme-stripe** [comment]
Sorry, should've marked this as draft, gotta run the nightly pipeline once first.

**Comment by jaimepark-stripe** [comment]
@davidme-stripe lmk when you need my stamp again

**Comment by davidme-stripe** [comment]
@jaimepark-stripe Ready now! I don't think we're going to get iOS 13.7 tests working, so we'll drop them and let the compiler watch out for any deprecations. :/

**Review by jaimepark-stripe — APPROVED** [review]

**Comment by Metin6201** [comment]
Danke

**Pull request merged**
