### PR TITLE
[WIP] Swift Package Manager, Xcode 12, and Apple Silicon support

### PR DESCRIPTION
**Pull request by davidme-stripe**
## Summary
* Add support for Swift Package Manager
* Move minimum version to iOS 11
* Add arm64 sim support

### Also:
* Remove deprecated StripeiOS-static scheme
* Remove deprecated iOS 10 code
* Build using Stripe3DS2.xcframework
* Move files around to fit SPM's preferred structure
* Add support for finding the Stripe bundle resources from an SPM bundle
* Move images to Asset Catalogs
* Add a Swift Package Manager install test
* Disable NSAsserts in the release version of Stripe.framework for consistency with Cocoapods and SPM (and a small binary size win)

## Motivation
#1255 

## Testing
Tested in CI, and with test projects on SPM and Cocoapods.

## TODO
- [x] Determine where to host Stripe3DS2.xcframework
- [x] Deploy smaller Stripe3DS2.xcframework and libStripe3DS2.a
- [x] Update Stripe3DS2 Catalyst slice
- [x] Test App Store submissions via TestFlight
- [x] Travis CI for Xcode 12 + SPM
- [x] Add this to the README.md along with errata
- [x] Move minimum version to iOS 11
- [x] arm64-ios-simulator slice for Stripe3DS2.xcframework
- [x] "found 20 file(s) which are unhandled; explicitly declare them as resources or exclude from the target"

### CODE REVIEW

**Comment by davidme-stripe** [comment]
Errata that we'll need to document, though I'm hoping these will be fixed before Xcode 12 is out:

* You may need to manually set "Embed & Sign" on Stripe in the "General" tab of your app's target settings.
* You may need to add the `-ObjC` linker flag in your app's build settings.
* I'm not sure if it's currently possible to bundle Stripe within another Swift PM package — for one thing, there isn't a way for our binary components to access the `SWIFTPM_MODULE_BUNDLE` macro set by SPM.

**Comment by kiiskristo** [comment]
Hi,
First thank you for making Stripe to support SPM.
Everything seems to work nicely on device and on simulator, but when using SwiftUI and trying to see the previews, then build failes, with error:
`clang: error: no such file or directory: '/Users/kristokiis/Library/Developer/Xcode/DerivedData/LeFood-gguutzvuzfxrwrbnagqarsfgasqd/Build/Intermediates.noindex/Previews/LeFood/Products/Debug-iphonesimulator/PackageFrameworks/Stripe.framework/Stripe'`

**Comment by davidme-stripe** [comment]
Thanks for the report, and sorry that we missed that! I'll try to get an arm64-ios-simulator slice built.

**Comment by davidme-stripe** [comment]
@kiiskristo The latest version has an arm64 slice, please try it out.

I've experienced some bugs with SPM's caching of binary frameworks, so to get the branch to update you may need to:
* Remove/re-add the library and/or package in Xcode
* Delete your project's ~/Library/Developer/Xcode/DerivedData folder
* Specify a specific commit ref in the package's options (it stores a commit ref in the .xcodeproj, and it sometimes doesn't update that ref when you specify a branch)

**Comment by davidme-stripe** [comment]
This patch was getting too big, so I split it into #1643 and #1644. These have been merged to the main branch, so I'm closing this out now.

**Pull request closed without merging**
