### PR TITLE
Adding support for the file uploads and personally identifiable information

### PR DESCRIPTION
**Pull request by scalessec**
## Summary

This PR adds file upload support for identity verification and evidence disputes. It also adds support for the tokenization of personally identifiable information (PII).

## Motivation

Hello again, @jack-stripe ! Over here at Zola we needed to add support for identity verification from our mobile client. We thought this would be a useful addition to the main repo. Here's a summary of the changes:

- `STPFile` - model object representing a file that has been upload to the Stripe API.
- `STPFileClient` - API client to upload a `UIImage` object for either identify verification or an evidence dispute.
- `STPMultipartFormDataPart` - Represents a single part of a `multipart/form-data` upload.
- `STPMultipartFormDataEncoder` - Transforms an array of `STPMultipartFormDataPart` objects into the HTTP body data required by a `multipart/form-data` upload.
- Added `createTokenWithPersonalIDNumber:completion:` to `STPAPIClient`.

## Example Usage

```swift
// Upload an identifying document
let client = STPFileClient(publishableKey: "pk_test_foo")
client.uploadImage(UIImage(named: "image")!, purpose: .identityDocument) { file, error in
     debugPrint(file, error)
}

// Tokenize a personal ID number
let client = STPAPIClient(publishableKey: "pk_test_foo")
client.createToken(withPersonalIDNumber: 000000000) { token, error in
     debugPrint(token, error)
}
```

## Testing

Your unit test target is currently broken on master (it looks like you're missing the `FBSnapshotTestCase` dependency). If you fix the target I'm happy to provide unit tests and functional tests for my additions.

### CODE REVIEW

**Comment by bdorfman-stripe** [comment]
Hi @scalessec,

Haven't had a chance to review this in depth yet, but we'll try to look over it soon and come to a decision on whether it is something we want to commit to supporting in the sdk.

As far as tests go, they should all be passing. You have to run `carthage bootstrap` to pull in dependencies, or use the scripts in the `ci_scripts` folder which some of this for you (and are what the Travis tests on this PR run).

**Comment by scalessec** [comment]
Sounds good. Let me know if you have questions. This is a pretty major requirement for our business now that we're moving to Stripe Connect so we'll most likely need to maintain a fork regardless.

**Comment by bdorfman-stripe** [comment]
Understood. If you have the bandwidth to add tests for your new code and also make sure all existing tests are passing (failing on the Travis builds right now), that would definitely help, as we would not be able to merge into master before then in any case.

**Comment by scalessec** [comment]
Just pushed tests for all my additions. Let me know if anything isn't clear.

**Comment by bdorfman-stripe** [comment]
Thanks for the tests. Although I think we probably do not actually want the functional tests, as we don't want tests that rely on internet connections or having hard-coded publishable keys in our repo. Also if you have a chance to fix the analyzer errors that are still showing up on the travis checks that would be great. 

I'll do an in-depth review of the PR later this week or next week.

**Comment by bdorfman-stripe** [comment]
Hey @scalessec, 

Sorry for the long delay in getting this reviewed. I think everything in here looks good. My only real feedback is:
1. Change the test image to something that might not be copyrighted :)
2. Fix the remaining test failures / merge conflicts.

If you can make those changes I think this can be merged in to our next release. Thanks again for your help in sending this to us, we really appreciate all the work you've done to improve our SDK!

**Comment by b20160** [comment]
Hey @scalessec  can you please resolve the current conflicts, I am looking forward to using your changes for my current app particularly the file upload. :)

**Comment by scalessec** [comment]
@b20160 I fixed the conflicts, but it looks like some changes in `master` broke the build. I should be able to make the required fixes tomorrow to wrap this up.

**Comment by b20160** [comment]
@scalessec Awesome Sauce, I will keep an eye out for it

**Comment by scalessec** [comment]
All green! w00t!

I swapped out the image for the file upload test with this:
https://www.pexels.com/photo/document-id-uk-driving-license-driving-licence-45113/
It's licensed under Creative Commons 0 (free for personal and commercial use with no attribution required).

Also, it might be worth adding a check from duplicate imports in `Stripe.h` inside `ci_scripts/check_public_headers.rb`. I spent an embarrassing amount of time trying to find the diff between `Stripe.h` and the `PublicHeaders` when if fact it was duplicate imports causing the script to fail.

**Comment by b20160** [comment]
@scalessec Thanks I am working on a really awesome app and this was kind of a block so thank you for your efforts someone give this man a medal. :)

**Comment by b20160** [comment]
do I have to wait for your branch to be merged before i can use it?

**Comment by scalessec** [comment]
@b20160 If you're using CocoaPods you'll need to wait for Stripe to merge the branch and cut a new release. If you're suing Carthage (or installing manually), you can _temporarily_ use my branch now (https://github.com/NewAmsterdamLabs/stripe-ios) and then switch it to the official repo after it's merged.

**Comment by bdorfman-stripe** [comment]
Ah good idea about the duplicate headers, sorry about that. Although we are trying to keep the header imports alphabetized, so if you could switch which duplicates you deleted that would be helpful.

This all looks great, thanks for your work on it, and sorry again about how long it took for me to properly review it. I'll get it merged in for our next release!

**Comment by scalessec** [comment]
Great, thanks!

**Comment by bdorfman-stripe** [comment]
Hey there are a few minor changes we'd like to make before merging. I think there is a setting on Github you can enable to let people with Stripe push access push commits to this branch. Could you turn this on for us, if you haven't already? https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by scalessec** [comment]
It's enabled, so in theory you should be able to commit.

**Comment by bdorfman-stripe** [comment]
Perfect, thanks!

**Comment by bdorfman-stripe** [comment]
@scalessec  Replacing this PR with a branch that is in our own repo for our own ease of committing. Can follow along at #586

**Pull request closed without merging**
