### PR TITLE
[Identity] - Butter 2.0 M1

### PR DESCRIPTION
**Pull request by ccen-stripe**
## Summary

Note this will serve as the release branch of butter 2.0, all further changes will be merged here before release.

This PR includes the following changes that are already reviewed:
* Support bottomsheet 
  * The upcoming project butter would introduce buttonsheet. This change adds support for bringing up bottomsheet with its data model. The bottom sheet will have dynamic height if the lines within doesn't occupy halfScreenHeight, and will make the lines scrollable and keep a maximum height if the lines went over.

* Support consent page
  * Apply bottomsheet for the consent page with new UX

* Replace doc selection screen with warm up screen

Related Android release branch: https://github.com/stripe/stripe-android/pull/7407

## Motivation

Better UX

## Testing

- [x] Unit test
- [x] Screenshot test
- [x] Manual test

## Recording
| Before  | After |
| ------------- | ------------- |
| before  | after |

### CODE REVIEW

**Comment by ccen-stripe** [comment]
@stripe/stripe-identity-observers

**Review by kgaidis-stripe — APPROVED** [review]

**Comment by ccen-stripe** [comment]
@stripe/stripe-identity-observers

**Comment by ccen-stripe** [comment]
This PR is reviewed and serves as the release branch, and the following reviewed and merged into this release branch:

https://github.com/stripe/stripe-ios/pull/2979

**Comment by kgaidis-stripe** [comment]
@ccen-stripe Does this need review, or should it be changed to a Draft PR (with assigners removed so there's no notifications)?

**Comment by ccen-stripe** [comment]
> @ccen-stripe Does this need review, or should it be changed to a Draft PR (with assigners removed so there's no notifications)?

@kgaidis-stripe all changes in this release branch are [reviewed](https://github.com/stripe/stripe-ios/pull/2964#issuecomment-1753993432), will merge them into master when we finished bugbash.

Will remove you from reviewer right now:)

**Review by kgaidis-stripe — APPROVED** [review]
rubber stamp - as per DM

**Pull request merged**
