### PR TITLE
Configure brand images

### PR DESCRIPTION
**Pull request by klaaspieter**
Useful for apps, like mine, that need to customize the brand images used by the card text field.

### CODE REVIEW

**Comment by jflinter** [comment]
Ah, neat. Thanks Klaas!

**Comment by bradfol** [comment]
@klaaspieter This implementation seems broken. The `cardBrand` parameter is just ignored in favor of the viewModel's state, which is computed based on the input in the text fields. 

Is this intended as a hook for override? If so, it seems the hook is implemented in the wrong place.

**Comment by klaaspieter** [comment]
@bradfol The methods were indeed meant to be just hooks that subclasses can override. They return the viewModel state because that was the behavior before my PR, in other words it didn't break any existing implementations.

**Comment by bradfol** [comment]
@klaaspieter I have submitted #284 that will allow for a similar hook (it is now a class method) while providing correct implementations of the new methods.

**Pull request merged**
